symfony/src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 */
class Client extends EntityBase
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="client", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientCartProduct", mappedBy="client", orphanRemoval=true)
     */
    private $CartProduct;

    public function __construct()
    {
        $this->CartProduct = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
    public function getName()
    {
        return $this->getUser()->getFirstname()." ".$this->getUser()->getLastname();
    }
    /**
     * @return Collection|ClientCartProduct[]
     */
    public function getCartProduct(): Collection
    {
        return $this->CartProduct;
    }
}

symfony/src/Entity/Sale.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SaleRepository")
 */
class Sale extends EntityBase
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $value;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Product", inversedBy="sale")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    public function getId()
    {
        return $this->id;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(Product $product): self
    {
        $this->product = $product;

        return $this;
    }
    /**
    Calculate price after sale to use it in twig and calculation
     */
    public function getAfterSale()
    {
        $before_sale =  $this->getProduct()->getPrice();
        return $before_sale-(($this->getValue()/100)*$before_sale);
    }
}

symfony/templates/pages/404.html.twig
{% extends 'bases/master.html.twig' %}

{% block title %}
    Page Not Found
{% endblock %}

{% block styles %}

{% endblock %}

{% block contents %}
    <header>
        {% include('includes/layouts/header-contact.html.twig') %}
    </header>
    ERROR 404 , Page Not Found
    {% include('includes/layouts/loading.html.twig') %}
{% endblock %}

{% block scripts %}
    <script src="ajax/carts.js"></script>
    <script>
        $(".filter li").click(function(){
            waiting();
            var category = $(this).data('id');
            if(category == "all") {
                $(".products .product").each(function () {
                    $(this).delay(500).show(1);
                });
            }
            else {
                $(".products .product .category").each(function () {
                    if ($(this).text().search(new RegExp(category, "i")) < 0) {
                        $(this).parent().delay(500).hide(1);
                    } else {
                        $(this).parent().delay(500).show(1);
                    }
                });
            }
            finish()
        });
    </script>
{% endblock %}

symfony/templates/pages/cart.html.twig
{% extends 'bases/master.html.twig' %}

{% block title %}
    {{ cart.name }}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{{ asset('css/cart.css') }}">
{% endblock %}

{% block contents %}
    <header>
{% include('includes/layouts/header-contact.html.twig') %}
    </header>
{% include('includes/forms/carts/update-quantity.html.twig') %}
    <section class="cart">
        <div class="container-fluid">
            <div class="col-md-8">
                {% set total = 0 %}
                {% set counter = 0 %}
                {% for cart_product in user.client.CartProduct %}
                    {% if cart_product.cart.id == cart.id %}
                        {% set counter = counter + 1 %}
                        <div class="cart-item">
                    <div class="fl-left">
                        <img src="{{ asset('images/product.jpg') }}" width="100" alt="">
                    </div>
                    <div class="fl-left caption">
                        <h4>
                            {{ cart_product.product.name }}
                        </h4>

                        <h4>Unit Price : <span class="text-blue">
                            {% if cart_product.product.sale %}
                                {{ cart_product.product.sale.afterSale }}
                                {% else %}
                                {{ cart_product.product.price }}
                                {% endif %}
                                LE
                            </span></h4>
                        <h4>Quantity : <span class="text-blue">
                                {{ cart_product.quantity }}
                                {% if cart.id == 1 %}
                                    <button style="margin-left: 10px"  data-id="{{ cart_product.id }}" data-popup="update-quantity" class="UpdateCart sm blue-btn">Update</button>
                                {% endif %}
                            </span>
                        </h4>
                        <h4>Sub Total : <span class="text-blue">{{ cart_product.getSubTotal }} LE</span></h4>
                        {% set total = total + cart_product.getSubTotal %}
                    </div>
                    <div class="clearfix"></div>
                    <div class="option text-right">
                        <button class="red-btn RemoveFromCart" data-id="{{ cart_product.id }}">Remove</button>
                    </div>
                </div>
                        {% endif %}
                    {% endfor %}
                {% if counter %}
                <button class="red-btn col-xs-12 EmptyCart" data-client="{{ user.client.id }}" data-cart="{{ cart.id }}">Empty Cart</button>
                {% endif %}
            </div>
            {% if cart.id == 1 and counter > 0 %}
            <div class="col-md-4">
                <div class="col-md-12 total">
                    Total:
                    <div class="amount">
                        {{ cart.total(1) }} LE
                    </div>
                </div>
                <button class="col-md-12 blue-btn">
                    Proceed To Checkout
                </button>
            </div>
            {% endif %}
            {% if counter == 0 %}
                <div class="col-xs-12">
                    <h1 class="text-center">Your Cart is Empty</h1>
                </div>
            {% endif %}
        </div>
</section>
{% endblock %}

{% block scripts %}
    <script src="{{ asset('ajax/carts.js') }}"></script>

{% endblock %}

symfony/templates/pages/carts.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
    Carts
{% endblock %}

{% block dashboard_style %}
{% endblock %}

{% block tab_contents %}
    {% include('includes/forms/carts/add.html.twig') %}
    <a href="{{ path('add_cart') }}"><button class="blue-btn AddButton">+</button></a>
    <div class="table-container">
        <div class="col-md-12"> <!-- search client -->
            <div class="col-md-12 filter" id="List-Filter"></div>
        </div>
        <table id="List-table" class="list-view text-center">
            <thead> <!-- main row -->
            <tr>
                <th>Name</th>
            </tr>
            </thead> <!-- main row -->
            <tbody>
            {% for cart in carts %}
                <tr>
                    <td>{{ cart.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            <div class="text-center pagination">

            </div>
        </div>
    </div>
{% endblock %}

{% block dashboard_scripts %}
    <script src="ajax/carts.js"></script>
{% endblock %}

symfony/templates/pages/categories.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
    Categories
{% endblock %}

{% block dashboard_style %}
{% endblock %}

{% block tab_contents %}
    <a href="{{ path('add_category') }}"><button class="blue-btn AddButton">+</button></a>
    <div class="table-container">
        <div class="col-md-12"> <!-- search client -->
            <div class="col-md-12 filter" id="List-Filter"></div>
        </div>
        <table id="List-table" class="list-view text-center">
            <thead> <!-- main row -->
            <tr>
                <th>Name</th>
                <th>Products</th>
            </tr>
            </thead> <!-- main row -->
            <tbody>
    {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ (category.products|length) }}</td>
            </tr>
        {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            <div class="text-center pagination">

            </div>
        </div>
    </div>
{% endblock %}

{% block dashboard_scripts %}
    <script src="ajax/categories.js"></script>
{% endblock %}

symfony/templates/pages/clients.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
    Clients
{% endblock %}

{% block dashboard_style %}
{% endblock %}

{% block tab_contents %}
    <div class="table-container">
        <div class="col-md-12"> <!-- search client -->
            <div class="col-md-12 filter" id="List-Filter"></div>
        </div>
        <table id="List-table" class="list-view text-center">
            <thead> <!-- main row -->
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Phone</th>
            </tr>
            </thead> <!-- main row -->
            <tbody>
            {% for client in clients %}
            <tr>
                <td>
                    {{ client.name }}
                </td>
                <td>
                    {{ client.address }}
                </td>
                <td>
                    {{ client.phone }}
                </td>
            </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            <div class="text-center pagination">

            </div>
        </div>
    </div>
{% endblock %}

{% block dashboard_scripts %}

{% endblock %}

symfony/templates/pages/home.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
Admin
{% endblock %}

{% block dashboard_style %}
{% endblock %}

{% block tab_contents %}
    <h2>Welcome to Your Control Panel</h2>
    <h4>In the future there will be some statistics</h4>
{% endblock %}

{% block dashboard_scripts %}

{% endblock %}

symfony/templates/pages/index.html.twig
{% extends 'bases/master.html.twig' %}

{% block title %}
    Home Page
{% endblock %}

{% block styles %}
    <style>
        section.products
        {
            min-height: 500px;
        }
        .filter li
        {
            display: block;
        }
    </style>
{% endblock %}

{% block contents %}
    <div class="alert" role="alert">
        <strong>Success!</strong> <div>Added To Cart</div>
    </div>    {% include('includes/forms/auth/signin.html.twig') %}
    {% include('includes/forms/auth/signup.html.twig') %}
    <header>
        {% include('includes/layouts/header-contact.html.twig') %}
        <section class="carts">
            <div class="container">
                <div class="fl-left">
                    <img width="150" src="images/logo.png" alt="">
                </div>
                <div class="fl-right carts">
                    {% for cart in carts %}
                    <a href="/cart/{{ cart.getId() }}">
                    <div class="cart fl-left">
                        <div class="fl-left" style="position: relative">
                            {% if cart.id == 1 %}
                                <i class="fas fa-shopping-bag" style="padding-top:2px"></i>
                            {% else %}
                                <i class="far fa-heart"></i>
                            {% endif %}
                        </div>
                        <div class="caption fl-left">
                            <div class="title">
                                {{ cart.name }}
                            </div>
                            <div class="amount text-light">
                                {%  if user  %}
                                    {% if user.role == "client" %}
                               <span id="Cart{{ cart.id }}">{{ cart.getTotal(user.getClient().id) }}</span>
                                {% endif %}
                                {% endif %}
                                {% if cart.id == 1 %}
                                LE
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    </a>
                    {% endfor %}
                </div>
                <div class="clearfix"></div>
            </div>
        </section>
        {% include('includes/layouts/header-nav.html.twig') %}
    </header>
    <section class="products">
        <div class="container">
            {% for product in products %}
            <div class="product col-md-3">
                <div class="category hidden">{{ product.category.id }}</div>
                <div class="header">
                    <div class="fl-left">
                        {% if product.sale %}
                        <span class="status status-sale">Sale</span>
                            {% endif %}
                    </div>
                    <div class="fl-right">
                        <i class=" pointer custom-hidden far fa-heart AddToCart" data-cart="2" data-product="{{ product.id }}" ></i>
                    </div>
                </div>
                <div class="image">
                    <img src="images/product.jpg" alt="">
                </div>
                <div class="caption text-center">
                    <h4>
                        {{ product.name }}
                    </h4>
                    <h4 class="text-blue">
                {% if product.sale %}
                    <span class="after-sale">{{ product.sale.afterSale }} LE</span>
                    <span class="before-sale text-light">{{ product.price }} LE</span>
                {% else %}
                    {{ product.price }} LE
                        {% endif %}
                    </h4>
                </div>
                <button data-product="{{ product.id }}" data-cart="1"  class="blue-btn AddToCart custom-hidden col-xs-12">
                    Add To Cart
                </button>
            </div>
            {% endfor %}
        </div>
    </section>
    {% include('includes/layouts/loading.html.twig') %}
{% endblock %}

{% block scripts %}
    <script src="ajax/auth.js"></script>
    <script src="ajax/carts.js"></script>
    <script>
        $(".filter li").click(function(){
            waiting();
            var category = $(this).data('id');
            if(category == "all") {
                $(".products .product").each(function () {
                    $(this).delay(500).show(1);
                });
            }
            else {
                $(".products .product .category").each(function () {
                    if ($(this).text().search(new RegExp(category, "i")) < 0) {
                        $(this).parent().delay(500).hide(1);
                    } else {
                        $(this).parent().delay(500).show(1);
                    }
                });
            }
            finish()
        });
    </script>
{% endblock %}

symfony/templates/pages/products.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
    Products
{% endblock %}

{% block dashboard_style %}
{% endblock %}

{% block tab_contents %}
    {% include('includes/forms/products/add.html.twig') %}
    <button class="blue-btn AddButton" data-popup="add-product">+</button>
    <div class="table-container">
        <div class="col-md-12"> <!-- search client -->
            <div class="col-md-12 filter" id="List-Filter"></div>
        </div>
        <table id="List-table" class="list-view text-center">
            <thead> <!-- main row -->
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Price</th>
            </tr>
            </thead> <!-- main row -->
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ (product.category.name) }}</td>
                    <td>{{ (product.quantity) }}</td>
                    <td>{{ (product.price) }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            <div class="text-center pagination">

            </div>
        </div>
    </div>
{% endblock %}

{% block dashboard_scripts %}
    <script src="ajax/products.js"></script>
{% endblock %}

symfony/templates/pages/sales.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
    Sales
{% endblock %}

{% block dashboard_style %}
    <style>
        #sale-result
        {
            display: none;
        }
    </style>
{% endblock %}

{% block tab_contents %}
    {% include('includes/forms/sales/add.html.twig') %}
    {% include('includes/forms/sales/delete.html.twig') %}
    <button class="blue-btn AddButton" data-popup="add-sale">+</button>
    <div class="table-container">
        <div class="col-md-12"> <!-- search client -->
            <div class="col-md-12 filter" id="List-Filter"></div>
        </div>
        <table id="List-table" class="list-view text-center">
            <thead> <!-- main row -->
            <tr>
                <th>Product</th>
                <th>Before Sale</th>
                <th>Sale Value</th>
                <th>After Sale</th>
                <th>Options</th>
            </tr>
            </thead> <!-- main row -->
            <tbody>
            {% for sale in sales %}
                <tr>
                    <td>{{ sale.product.name }}</td>
                    <td>{{ sale.product.price }}</td>
                    <td>{{ (sale.value) }}</td>
                    <td>{{ (sale.afterSale) }}</td>
                    <td>
                        <i class="fa fa-times white delete-sale" data-id="{{ sale.id }}" data-popup="delete-sale"></i>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="text-center">
            <div class="text-center pagination">

            </div>
        </div>
    </div>
{% endblock %}

{% block dashboard_scripts %}
    <script src="ajax/sales.js"></script>
{% endblock %}

symfony/templates/pages/settings.html.twig
{% extends 'bases/dashboard.html.twig' %}

{% block title %}
    Categories
{% endblock %}

{% block dashboard_style %}
{% endblock %}

{% block tab_contents %}

{% endblock %}

{% block dashboard_scripts %}

{% endblock %}